### ISSUE TITLE
istft has bug,  return [] , code as follow , lws version 1.2.8

### ISSUE THREAD

**Issue by ouleiwa** [Jonathan-LeRoux/lws#17]
#From https://github.com/r9y9/wavenet_vocoder/blob/master/audio.py

def inv_linear_spectrogram(linear_spectrogram, hparams):
	'''Converts linear spectrogram to waveform using librosa'''
	if hparams.signal_normalization:
		D = _denormalize(linear_spectrogram, hparams)
	else:
		D = linear_spectrogram

	S = _db_to_amp(D + hparams.ref_level_db) #Convert back to linear

	if hparams.use_lws:
		processor = _lws_processor(hparams)
		D = processor.run_lws(S.astype(np.float64).T ** hparams.power)
		y = processor.istft(D).astype(np.float32)  #error: return void []
		return y
	else:
		return _griffin_lim(S ** hparams.power, hparams)
	

# lws init params:  nfft = 1024 ， win_hop=256, win_size =1024, mode = "speech"

**Comment by Jonathan-LeRoux** [comment]
Could you please elaborate?

I don't see anywhere where `lws` is used in the [wavenet_vocoder](https://github.com/r9y9/wavenet_vocoder/blob/master/audio.py) repo.

Also, is this a new issue since the recently updated version 1.2.8, or did it exist prior to that as well?

**Comment by ouleiwa** [comment]
> Could you please elaborate?
> 
> I don't see anywhere where `lws` is used in the [wavenet_vocoder](https://github.com/r9y9/wavenet_vocoder/blob/master/audio.py) repo.
> 
> Also, is this a new issue since the recently updated version 1.2.8, or did it exist prior to that as well?

sorry， I made a mistake with the repos address.  
the right address is https://github.com/Rayhane-mamah/Tacotron-2/blob/ab5cb08a931fc842d3892ebeb27c8b8734ddd4b8/datasets/audio.py#L147.  And， I have fixed this bug by using version 1.2.0 of lws.

I think you can simply replicate the bug by using code as follow:

import lws  # version 1.2.8
import numpy as np
params.nfft = 1024 ， params.win_hop=256, params.win_size =1024, params.mode = "speech"
processor  = lws.lws(hparams.n_fft,params.win_hop,fftsize=hparams.win_size, mode="speech")
S = np.random.randn(2000)
D = processor.run_lws(S.astype(np.float64))
y = processor.istft(D).astype(np.float32)

**Comment by Jonathan-LeRoux** [comment]
I'm still not getting a bug with 1.2.8 with the following code:
```
import lws # version 1.2.8
import numpy as np
nfft=1024
win_hop=256
win_size=1024
mode = "speech"
processor = lws.lws(nfft,win_hop,fftsize=win_size, mode="speech")
s = np.random.randn(2000)
S = processor.stft(s)
D = processor.run_lws(S.astype(np.float64))
y = processor.istft(D).astype(np.float32)
```

**Comment by ouleiwa** [comment]
sorry，I can't reproduce it either, maybe there was a problem elsewhere before
